Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -339,7 +339,7 @@ jobs:
             echo "${API_URL}"
             if curl -s $API_URL/api/status | grep "ok"
             then
-              exit 1
+              exit 0
             else
               exit 1
             fi   
@@ -350,7 +350,7 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0 # will convert it to 0 after failure 
+              exit 1 # will convert it to 0 after failure 
             else
               exit 1
             fi  
